export const FETCH_PRODYCTS_START = 'FETCH_PRODYCTS_START';
export const FETCH_PRODYCTS_SUCCESS = 'FETCH_PRODYCTS_SUCCESS';
export const FETCH_PRODYCTS_FAIL = 'FETCH_PRODYCTS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';